### ISSUE TITLE
poor ipc throughput

### ISSUE THREAD

**Issue by zhjie233** [dicej/ipmpsc#8]
Thanks for contributing this really user-friendly crate.
In my test, ipmpsc shows low latency when using small messages(about 10 bytes), but the latency grows dramatically with bigger ones (8192 bytes).

In detail,
- send "hello world" - recv "hello": about 5 us(micro sec) and 0.4 us(busy polling) for each time.
- send 8192 bytes - recv 8192  bytes: about 70 us for each time.
   - In fact, this performance is much lower than that of unix domain socket.
   
I'm wondering if this is normal or should be something wrong with my usage.

**Comment by dicej** [comment]
Thanks for reporting this.  You're using Linux, I assume?  [perf](https://perf.wiki.kernel.org/index.php/Main_Page) may help diagnose the problem.

I haven't benchmarked latency yet -- just throughput -- so there could definitely be an issue here.  If you can post some working example code which exhibits the problem, I'd be happy to take a look.

**Comment by zhjie233** [comment]
[Here ](https://github.com/TOPbuaa/rust_ipc_examples) is my test code. Thanks.

**Comment by dicej** [comment]
@TOPbuaa Using `serde_bytes` makes a big difference, and I believe it addresses the performance issue you're seeing: https://github.com/TOPbuaa/rust_ipc_examples/pull/1

**Comment by zhjie233** [comment]
> 

Thank you so much, this works great and does solve my problem. I will close this issue.
